item {
  id: 1
  name: 'tshirt'
}

item {
  id: 2
  name: 'jeans'
}

item {
  id: 3
  name: 'etek'
}

item {
  id: 4
  name: 'sort'
}

item {
  id: 5
  name: 'ceket'
}

item {
  id: 6
  name: 'kravat'
}

item {
  id: 7
  name: 'sapka'
}

item {
  id: 8
  name: 'abiye'
}